version: "3"

vars:
  EWW_DIR: "{{.PWD}}"
  RUST_APPLETS: "{{.EWW_DIR}}/rust-applets"

tasks:
  # ============================================================================
  # BUILD TASKS
  # ============================================================================

  build:
    desc: Build all Rust applets
    deps:
      - build:battery
      - build:bluetooth
      - build:brightness
      - build:keyboard
      - build:network
      - build:notifications
      - build:power
      - build:updates
      - build:user-info
      - build:weather
      - build:workspaces
      - build:window-title
      - build:pomodoro
      - build:mixer
      - build:music-daemon

  build:battery:
    desc: Build battery monitor
    dir: "{{.RUST_APPLETS}}/eww-battery"
    sources:
      - "src/**/*.rs"
      - "Cargo.toml"
    generates:
      - "target/release/eww-battery"
    cmds:
      - cargo build --release

  build:workspaces:
    desc: Build workspaces monitor
    dir: "{{.RUST_APPLETS}}/eww-workspaces"
    sources:
      - "src/**/*.rs"
      - "Cargo.toml"
    generates:
      - "target/release/eww-workspaces"
    cmds:
      - cargo build --release

  build:window-title:
    desc: Build window title monitor
    dir: "{{.RUST_APPLETS}}/eww-window-title"
    sources:
      - "src/**/*.rs"
      - "Cargo.toml"
    generates:
      - "target/release/eww-window-title"
    cmds:
      - cargo build --release

  build:pomodoro:
    desc: Build pomodoro timer
    dir: "{{.RUST_APPLETS}}/eww-pomodoro"
    sources:
      - "src/**/*.rs"
      - "Cargo.toml"
    generates:
      - "target/release/eww-pomodoro"
    cmds:
      - cargo build --release

  build:mixer:
    desc: Build unified audio mixer (volume + microphone)
    dir: "{{.RUST_APPLETS}}/eww-mixer"
    sources:
      - "src/**/*.rs"
      - "Cargo.toml"
    generates:
      - "target/release/eww-mixer"
    cmds:
      - cargo build --release

  build:music-daemon:
    desc: Build music daemon
    dir: "{{.RUST_APPLETS}}/eww-music-daemon"
    sources:
      - "src/**/*.rs"
      - "Cargo.toml"
    generates:
      - "target/release/eww-music-daemon"
    cmds:
      - cargo build --release

  build:bluetooth:
    desc: Build bluetooth monitor
    dir: "{{.RUST_APPLETS}}/eww-bluetooth"
    sources:
      - "src/**/*.rs"
      - "Cargo.toml"
    generates:
      - "target/release/eww-bluetooth"
    cmds:
      - cargo build --release

  build:brightness:
    desc: Build brightness monitor
    dir: "{{.RUST_APPLETS}}/eww-brightness"
    sources:
      - "src/**/*.rs"
      - "Cargo.toml"
    generates:
      - "target/release/eww-brightness"
    cmds:
      - cargo build --release

  build:keyboard:
    desc: Build keyboard layout monitor
    dir: "{{.RUST_APPLETS}}/eww-keyboard"
    sources:
      - "src/**/*.rs"
      - "Cargo.toml"
    generates:
      - "target/release/eww-keyboard"
    cmds:
      - cargo build --release

  build:network:
    desc: Build network monitor
    dir: "{{.RUST_APPLETS}}/eww-network"
    sources:
      - "src/**/*.rs"
      - "Cargo.toml"
    generates:
      - "target/release/eww-network"
    cmds:
      - cargo build --release

  build:notifications:
    desc: Build notifications monitor
    dir: "{{.RUST_APPLETS}}/eww-notifications"
    sources:
      - "src/**/*.rs"
      - "Cargo.toml"
    generates:
      - "target/release/eww-notifications"
    cmds:
      - cargo build --release

  build:power:
    desc: Build power menu
    dir: "{{.RUST_APPLETS}}/eww-power"
    sources:
      - "src/**/*.rs"
      - "Cargo.toml"
    generates:
      - "target/release/eww-power"
    cmds:
      - cargo build --release

  build:updates:
    desc: Build updates monitor
    dir: "{{.RUST_APPLETS}}/eww-updates"
    sources:
      - "src/**/*.rs"
      - "Cargo.toml"
    generates:
      - "target/release/eww-updates"
    cmds:
      - cargo build --release

  build:user-info:
    desc: Build user info widget
    dir: "{{.RUST_APPLETS}}/eww-user-info"
    sources:
      - "src/**/*.rs"
      - "Cargo.toml"
    generates:
      - "target/release/eww-user-info"
    cmds:
      - cargo build --release

  build:weather:
    desc: Build weather widget
    dir: "{{.RUST_APPLETS}}/eww-weather"
    sources:
      - "src/**/*.rs"
      - "Cargo.toml"
    generates:
      - "target/release/eww-weather"
    cmds:
      - cargo build --release

  # ============================================================================
  # EWW MANAGEMENT TASKS
  # ============================================================================

  reload:
    desc: Reload EWW configuration
    deps:
      - build
    cmds:
      - eww reload
      - echo "✓ EWW reloaded"

  restart:
    desc: Restart EWW completely
    deps:
      - build
    cmds:
      - task: kill
      - sleep 1
      - eww daemon
      - sleep 1
      - eww open bar
      - echo "✓ EWW restarted"

  open:
    desc: Open EWW bar
    cmds:
      - eww open bar
      - echo "✓ EWW bar opened"

  close:
    desc: Close all EWW windows
    cmds:
      - eww close-all
      - echo "✓ All EWW windows closed"

  kill:
    desc: Kill EWW daemon and all associated processes
    cmds:
      - eww kill || true
      - pkill -f 'eww-pomodoro daemon' || true
      - pkill -f 'eww-mixer listen' || true
      - pkill -f 'eww-music-daemon' || true
      - rm -f /tmp/eww-pomodoro.sock || true
      - rm -f /tmp/eww-mixer.sock || true
      - echo "✓ EWW and all daemons killed"

  logs:
    desc: Show EWW logs
    cmds:
      - tail -f ~/.cache/eww/eww_*.log

  # ============================================================================
  # DEVELOPMENT TASKS
  # ============================================================================

  dev:
    desc: Development mode - watch and reload on changes
    deps:
      - build
    cmds:
      - echo "Watching for changes..."
      - |
        while true; do
          inotifywait -e modify -r {{.EWW_DIR}}/eww.yuck {{.EWW_DIR}}/config.yuck {{.EWW_DIR}}/styles/ &&
          eww reload &&
          echo "✓ Reloaded at $(date)"
        done

  check:
    desc: Check all Rust code
    cmds:
      - |
        for dir in {{.RUST_APPLETS}}/*/; do
          echo "Checking $(basename $dir)..."
          (cd "$dir" && cargo check)
        done

  fmt:
    desc: Format all Rust code
    cmds:
      - |
        for dir in {{.RUST_APPLETS}}/*/; do
          echo "Formatting $(basename $dir)..."
          (cd "$dir" && cargo fmt)
        done

  clean:
    desc: Clean all build artifacts
    cmds:
      - |
        for dir in {{.RUST_APPLETS}}/*/; do
          echo "Cleaning $(basename $dir)..."
          (cd "$dir" && cargo clean)
        done
      - echo "✓ All build artifacts cleaned"

  # ============================================================================
  # TESTING TASKS
  # ============================================================================

  test:battery:
    desc: Test battery monitor
    cmds:
      - "{{.RUST_APPLETS}}/eww-battery/target/release/eww-battery | jq"

  test:workspaces:
    desc: Test workspaces monitor (Ctrl+C to stop)
    cmds:
      - "{{.RUST_APPLETS}}/eww-workspaces/target/release/eww-workspaces"

  test:window-title:
    desc: Test window title monitor (Ctrl+C to stop)
    cmds:
      - "{{.RUST_APPLETS}}/eww-window-title/target/release/eww-window-title listen"

  test:pomodoro:
    desc: Test pomodoro timer (Ctrl+C to stop)
    cmds:
      - "{{.RUST_APPLETS}}/eww-pomodoro/target/release/eww-pomodoro listen"

  test:mixer:
    desc: Test unified mixer (Ctrl+C to stop)
    cmds:
      - "{{.RUST_APPLETS}}/eww-mixer/target/release/eww-mixer listen | jq"

  test:music:
    desc: Test music daemon (Ctrl+C to stop)
    cmds:
      - "{{.RUST_APPLETS}}/eww-music-daemon/target/release/eww-music-daemon listen"

  # ============================================================================
  # UTILITY TASKS
  # ============================================================================

  status:
    desc: Show status of all daemons
    cmds:
      - |
        echo "=== EWW Status ==="
        if pgrep -f 'eww daemon' > /dev/null; then
          echo "✓ EWW daemon: running"
        else
          echo "✗ EWW daemon: not running"
        fi

        echo ""
        echo "=== Rust Daemon Status ==="

        if pgrep -f 'eww-pomodoro daemon' > /dev/null; then
          echo "✓ Pomodoro daemon: running"
        else
          echo "✗ Pomodoro daemon: not running"
        fi

        if pgrep -f 'eww-mixer listen' > /dev/null; then
          echo "✓ Unified Mixer daemon: running"
        else
          echo "✗ Unified Mixer daemon: not running"
        fi

        if pgrep -f 'eww-music-daemon' > /dev/null; then
          echo "✓ Music daemon: running"
        else
          echo "✗ Music daemon: not running"
        fi

  default:
    desc: Show available tasks
    cmds:
      - task --list
